#!/bin/bash
cd `dirname $0`

source virtualenvwrapper.sh

# virtualenvwrapper doesn't work with "set -e
function check_worked {
    if ! $*
    then
        exit 1
    fi
}

echo Django 1.4
cd test-projects/django1_4
workon fost-auth-1.4
check_worked python ./manage.py test fost_authn fost_authn_debug

echo Django 1.7
cd ../django1_7
workon fost-auth-1.7
check_worked python ./manage.py test fost_authn fost_authn_debug
